apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/allenvino1/k8s-playground.git
    targetRevision: HEAD
    path: argocd/microservice-sample/chart
    helm:
      releaseName: microservice-sample
      valueFiles:
      - ../../envs/devx.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: devx
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true